module.exports = {
	'extends': [
		'eslint:recommended',
	],
	'rules': {
		// possible errors
		'no-async-promise-executor': ['error'],
		'no-await-in-loop': ['error'],
		'no-console': ['off'],
		'no-prototype-builtins': ['error'],
		'require-atomic-updates': ['error'],
		// best practices
		'block-scoped-var': ['error'],
		'curly': ['error'],
		'default-case': ['error'],
		'dot-location': ['error', 'property'],
		'dot-notation': ['error'],
		'eqeqeq': ['error'],
		'guard-for-in': ['error'],
		'no-caller': ['error'],
		'no-extend-native': ['error'],
		'no-extra-bind': ['error'],
		'no-extra-label': ['error'],
		'no-floating-decimal': ['error'],
		'no-implied-eval': ['error'],
		'no-iterator': ['error'],
		'no-multi-spaces': ['error'],
		'no-new-wrappers': ['error'],
		'no-octal-escape': ['error'],
		'no-proto': ['error'],
		'no-return-assign': ['error'],
		'no-return-await': ['error'],
		'no-self-compare': ['error'],
		'no-sequences': ['error'],
		'no-throw-literal': ['error'],
		'no-useless-catch': ['error'],
		'no-useless-concat': ['error'],
		'no-useless-return': ['error'],
		'no-with': ['error'],
		'prefer-promise-reject-errors': ['error', {
			'allowEmptyReject': true,
		}],
		'radix': ['error'],
		'wrap-iife': ['error', 'any'],
		'yoda': ['error'],
		// variables
		'no-label-var': ['error'],
		'no-shadow': ['error'],
		'no-shadow-restricted-names': ['error'],
		'no-unused-vars': ['error', {
			'ignoreRestSiblings': true,
		}],
		'no-use-before-define': ['error'],
		// es6
		'arrow-parens': ['error', 'always'],
		'arrow-spacing': ['error'],
		'generator-star-spacing': ['error'],
		'no-confusing-arrow': ['error', {
			'allowParens': true,
		}],
		'no-duplicate-imports': ['error'],
		'no-useless-computed-key': ['error'],
		'no-useless-constructor': ['error'],
		'no-useless-rename': ['error'],
		'no-var': ['error'],
		'object-shorthand': ['error', 'always', {
			'avoidQuotes': true,
		}],
		'prefer-arrow-callback': ['error', {
			'allowNamedFunctions': true,
		}],
		'prefer-const': ['error', {
			'ignoreReadBeforeAssign': true,
		}],
		'prefer-numeric-literals': ['error'],
		'prefer-rest-params': ['error'],
		'prefer-spread': ['error'],
		'prefer-template': ['error'],
		'rest-spread-spacing': ['error'],
		'symbol-description': ['error'],
		'template-curly-spacing': ['error'],
		'yield-star-spacing': ['error'],
		// stylistic
		'array-bracket-newline': ['error', 'consistent'],
		'array-bracket-spacing': ['error', 'never'],
		'array-element-newline': ['error', 'consistent'],
		'block-spacing': ['error', 'always'],
		'brace-style': ['error', 'stroustrup'],
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', {
			'before': false,
			'after': true,
		}],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'eol-last': ['error'],
		'func-call-spacing': ['error', 'never'],
		'func-names': ['error', 'as-needed'],
		'function-paren-newline': ['error', 'consistent'],
		'implicit-arrow-linebreak': ['error', 'beside'],
		'indent': ['error', 'tab', {
			'SwitchCase': 1,
		}],
		'jsx-quotes': ['error', 'prefer-double'],
		'key-spacing': ['error', {
			'beforeColon': false,
			'afterColon': true,
			'mode': 'strict',
		}],
		'keyword-spacing': ['error', {
			'before': true,
			'after': true,
		}],
		'linebreak-style': ['error', 'unix'],
		'lines-between-class-members': ['error', 'always'],
		'max-statements-per-line': ['error', {
			'max': 1,
		}],
		'multiline-comment-style': ['error', 'starred-block'],
		'new-parens': ['error'],
		'no-array-constructor': ['error'],
		'no-bitwise': ['error'],
		'no-lonely-if': ['error'],
		'no-mixed-operators': ['error'],
		'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		'no-multi-assign': ['error'],
		'no-multiple-empty-lines': ['error', {
			'max': 2,
		}],
		'no-nested-ternary': ['error'],
		'no-new-object': ['error'],
		'no-tabs': ['error', {
			'allowIndentationTabs': true,
		}],
		'no-trailing-spaces': ['error', {
			'skipBlankLines': true,
		}],
		'no-underscore-dangle': ['error'],
		'no-unneeded-ternary': ['error'],
		'no-whitespace-before-property': ['error'],
		'object-curly-spacing': ['error', 'always'],
		'object-property-newline': ['error'],
		'one-var': ['error', 'never'],
		'one-var-declaration-per-line': ['error', 'always'],
		'operator-assignment': ['error', 'always'],
		'operator-linebreak': ['error', 'after', {
			'overrides': {
				'?': 'before',
				':': 'before',
			},
		}],
		'padded-blocks': ['error', 'never'],
		'prefer-object-spread': ['error'],
		'quote-props': ['error', 'always'],
		'quotes': ['error', 'single', {
			'avoidEscape': true,
			'allowTemplateLiterals': true,
		}],
		'semi': ['error', 'always'],
		'semi-spacing': ['error', {
			'before': false,
			'after': true,
		}],
		'semi-style': ['error', 'last'],
		'space-before-blocks': ['error', 'always'],
		'space-before-function-paren': ['error', 'always'],
		'space-in-parens': ['error', 'never'],
		'space-infix-ops': ['error'],
		'space-unary-ops': ['error', {
			'words': true,
			'nonwords': false,
		}],
		'switch-colon-spacing': ['error'],
		'template-tag-spacing': ['error', 'never'],
		'unicode-bom': ['error'],
	},
};
